modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/refinedmods/refinedpipes"
license="MIT"
[[mods]]
modId="refinedpipes"
version="${version}"
displayName="Refined Pipes"
displayURL="https://refinedmods.com/refined-pipes"
authors="Refined Mods"
description='''
Refined Pipes is a Minecraft mod that adds pipes.
'''
